/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Product service. Represents a row in the &quot;panasonic_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.product.model.impl.ProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.product.model.impl.ProductImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Product
 * @generated
 */
@ProviderType
public interface ProductModel
	extends BaseModel<Product>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product.
	 *
	 * @return the uuid of this product
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product.
	 *
	 * @param uuid the uuid of this product
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this product.
	 *
	 * @return the product ID of this product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product.
	 *
	 * @param productId the product ID of this product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the group ID of this product.
	 *
	 * @return the group ID of this product
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this product.
	 *
	 * @param groupId the group ID of this product
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product.
	 *
	 * @return the company ID of this product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product.
	 *
	 * @param companyId the company ID of this product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the product cost of this product.
	 *
	 * @return the product cost of this product
	 */
	public long getProductCost();

	/**
	 * Sets the product cost of this product.
	 *
	 * @param productCost the product cost of this product
	 */
	public void setProductCost(long productCost);

	/**
	 * Returns the product name of this product.
	 *
	 * @return the product name of this product
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product.
	 *
	 * @param productName the product name of this product
	 */
	public void setProductName(String productName);

	/**
	 * Returns the create date of this product.
	 *
	 * @return the create date of this product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product.
	 *
	 * @param createDate the create date of this product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product.
	 *
	 * @return the modified date of this product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product.
	 *
	 * @param modifiedDate the modified date of this product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this product.
	 *
	 * @return the field1 of this product
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this product.
	 *
	 * @param field1 the field1 of this product
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this product.
	 *
	 * @return the field2 of this product
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this product is field2.
	 *
	 * @return <code>true</code> if this product is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this product is field2.
	 *
	 * @param field2 the field2 of this product
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this product.
	 *
	 * @return the field3 of this product
	 */
	public int getField3();

	/**
	 * Sets the field3 of this product.
	 *
	 * @param field3 the field3 of this product
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this product.
	 *
	 * @return the field4 of this product
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this product.
	 *
	 * @param field4 the field4 of this product
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this product.
	 *
	 * @return the field5 of this product
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this product.
	 *
	 * @param field5 the field5 of this product
	 */
	public void setField5(String field5);

}